<?=$this->render('header.phtml');?>
<style type="text/css">
.popover {max-width:90%;}
</style>
<div class="container-fluid">
  <div class="row mt-3">
    <div class="col-auto mr-auto">
      <h3>检查更新</h3>
    </div>
    <div class="col-auto">
      <a class="btn btn-primary" href="new" role="button">更 新</a>
      <a class="btn btn-light" href="javascript:window.history.back();" role="button">返 回</a>
    </div>
  </div>
  <hr />
  <?=$this->render('alert.phtml');?>
  <div>
    <?php $i = 0; foreach ($changes as $section => $items) { ?>
    <h4 class="mt-3"><?=$section;?></h4>
    <hr />
    <div class="row">
      <?php foreach ($items as $item) { ?>
      <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
        <i class="fa fa-<?=$status_icons[$item['status']];?>" aria-hidden="true"></i> <?=$item['name'];?>
        <a tabindex="<?=$i++;?>" class="badge badge-light badge-pill" data-toggle="popover" data-trigger="focus" data-html="true" title="<?=$section.': '.$item['name'];?>" data-content="<?=nl2br(htmlspecialchars(htmlspecialchars($item['content'])));?>" style="cursor:help;"><?=$item['count'];?></a>
      </div>
      <?php } ?>
    </div>
    <?php } ?>
  </div>
</div>
<script type="text/javascript" language="JavaScript">
$(function() {
    if ($('[role="alert"]').length > 0) {
        $('.btn-primary').hide();
    }
    $('[data-toggle="popover"]').popover();
});
</script>
<?=$this->render('footer.phtml');?>