<?=$this->render('header.phtml');?>
<div class="container-fluid">
  <div class="row mt-3">
    <div class="col-auto mr-auto">
      <h3>版本历史</h3>
    </div>
    <div class="col-auto">
      <a id="checkBtn" href="diff" class="btn btn-primary" role="button"><i class="fa fa-search" aria-hidden="true"></i> 检查更新</a>
    </div>
  </div>
  <?=$this->render('alert.phtml');?>
  <?php foreach ($commits as $commit) { ?>
  <hr />
  <div class="row">
    <div class="col">
      <i class="fa fa-calendar" aria-hidden="true"></i> <?=$commit->create_date;?>
    </div>
    <div class="col-6">
      <strong><?=$commit->message;?></strong><br />
      <?=$commit->author;?> authored <span data-toggle="tooltip" data-placement="top" title="<?=$commit->create_time;?>"><?=$commit->time_elapsed;?></span>
    </div>
    <div class="col">
      <?=$commit->short_id;?><br />
      <a href="version/<?=$commit->version;?>">Browse »</a>
    </div>
  </div>
  <?php } ?>
</div>
<script type="text/javascript" language="JavaScript">
$(function () {
    $('[data-toggle="tooltip"]').tooltip();
    if ($('.alert-danger').length > 0) {
        $('#checkBtn').addClass('disabled').hide();
    }
});
</script>
<?=$this->render('footer.phtml');?>