<?=$this->render('header.phtml');?>
<div class="container-fluid">
  <div class="row mt-3">
    <div class="col-auto mr-auto">
      <h3>提交新版本</h3>
    </div>
  </div>
  <hr />
  <?=$this->render('alert.phtml');?>
  <form id="commitForm" action="new" method="POST">
    <div class="form-group row">
      <label for="author" class="col-sm-2 col-form-label">提交人：</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="author" name="author"  required />
      </div>
    </div>
    <div class="form-group row">
      <label for="message" class="col-sm-2 col-form-label">备注：</label>
      <div class="col-sm-10">
        <textarea class="form-control" id="message" name="message" required></textarea>
      </div>
    </div>
    <div class="row">
      <label for="content" class="col-sm-2 col-form-label">SQL：</label>
      <div class="col-sm-10">
        <textarea class="form-control" id="content" name="content" rows="10" required><?=$content;?></textarea>
      </div>
    </div>
    <div class="row justify-content-end mt-3">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary" id="submitBtn">提 交</button>
        <a class="btn btn-secondary" href="javascript:window.history.back();" role="button">返 回</a>
      </div>
    </div>
  </form>
</div>
<script type="text/javascript" language="JavaScript">
$(function () {
    // $('#backBtn').click(function() {
    //     window.history.back();
    // });
});
</script>
<?=$this->render('footer.phtml');?>